kind = "DojoContract"
class_hash = "0x7074d9c4ee72049ceda4e3c1d3246744caae55dbcf61b78526832bc899055ef"
original_class_hash = "0x7074d9c4ee72049ceda4e3c1d3246744caae55dbcf61b78526832bc899055ef"
base_class_hash = "0x0"
abi = "manifests/mainnet/base/abis/contracts/flippyflop-actions-4407e5f5.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-actions"
systems = [
    "flip",
    "flop",
    "claim",
]
manifest_name = "flippyflop-actions-4407e5f5"
